name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Testing ${{matrix.os}} Python ${{matrix.python-version}}, with Numpy ${{matrix.numpy-version}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11', '3.12']
        numpy-version: ['1', '2']

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dev
          environment-file: ./environment.yaml
          python-version: ${{ matrix.python-version }}
      - run: pip install . -v
      - run: make test python=python
      - run: make format python=python
      - run: make build python=python
      - run: make test-dist python=python
