name: Test MacOS

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Testing
    runs-on: ["macos-latest"]
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v2
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     activate-environment: dev
      #     environment-file: ./environment.yaml
      #     python-version: ${{ matrix.python-version }}
      - run: which brew
      - run: brew ls --versions gcc
      - run: brew ls --versions gfortran
      - run: brew install gcc openblas lapack
      - run: ls /opt/homebrew/bin/
      - run: which gfortran-14
      - run: pip install -r ./requirements.txt
      - run: FC=gfortran-14 pip install . -v
      - run: make test python=python
      - run: make format python=python
      - run: make build python=python
      - run: make test-dist python=python
