name: Test MacOS

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Testing ${{matrix.os}} py-${{matrix.python-version}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: ['macos-latest']
        python-version: ['3.11','3.12']

    steps:
      - uses: actions/checkout@v2
      - run: which brew
      - run: brew install gcc openblas lapack libomp
      - run: ls /opt/homebrew/bin/
      - run: which gfortran-14

      # TODO Setup uv

      - run: pip install -r ./requirements.txt

      - run: FC=gfortran-14 pip install . -v
      - run: make test python=python
      - run: make format python=python
      - run: FC=gfortran-14 make build python=python
      - run: make test-dist python=python
